dist: xenial
language: minimal

services:
  - docker

env:
  global:
    - SLUG="${TRAVIS_REPO_SLUG/docker-/}"
    # - VER=$(echo ${TRAVIS_TAG} | cut -d. -f1,2)
    # - DIR=$(ls -vd */ | grep '^[0-9]' | tail -n 1 | tr -d /)
    # - PREFIX="${VER:-$DIR}"

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

stages:
  - build
  - test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: build
      script:
        - docker build -t ${SLUG} .
        - docker inspect --type=image ${SLUG}

    - stage: test
      script:
        - docker run --name ${SLUG/!(\/)\/} -d -p 5050:5050 ${SLUG}
        - sleep 60 # Wait for server to finish starting up.
        - docker logs ${SLUG/!(\/)\/}
