dist: xenial
#addons:
#  chrome: stable

services:
  - docker

language: minimal

#docker: Error response from daemon: Invalid container name (noaho/docker-couchpotato), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed.

env:
  global:
    - SLUG="${TRAVIS_REPO_SLUG/docker-/}"
    # - VER=$(echo ${TRAVIS_TAG} | cut -d. -f1,2)
    # - DIR=$(ls -vd */ | grep '^[0-9]' | tail -n 1 | tr -d /)
    # - PREFIX="${VER:-$DIR}"

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - env #Show environment variables
  - docker build -t ${SLUG} .
  - docker run --name ${SLUG/!(\/)\/} -d -p 5050:5050 ${SLUG}
  - docker inspect --type=image ${SLUG}
  - sleep 60 # Wait for server to finish starting up.
  - docker logs ${SLUG/!(\/)\/}
  # Test web port is accessible.
#https://docs.travis-ci.com/user/gui-and-headless-browsers/
#- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
# Set up weekly cron jobs to test

# Set up notifications via email or phone on failed builds.
